version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - laravel
      - mailhog
    working_dir: /var/www/portfolio
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl/server.crt:/etc/nginx/ssl/server.crt
      - ./docker/nginx/ssl/server.key:/etc/nginx/ssl/server.key
      - ./docker/nginx/ssl/server.password:/etc/nginx/ssl/server.password
      - .:/var/www/portfolio:cached
    restart: on-failure

  laravel:
    build: ./docker/laravel
    working_dir: /var/www/portfolio
    ports:
      - "5173:5173"
    volumes:
      - ./docker/laravel/src/php.ini:/usr/local/etc/php/php.ini
      - ./docker/laravel/src/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - .:/var/www/portfolio:cached

  node:
    image: node:20
    working_dir: /var/www/portfolio
    ports:
      - "3001:3001"
      - "3002:3002"
    volumes:
      - .:/var/www/portfolio:cached
    command: npm help

  redis:
    image: "redis:latest"
    restart: on-failure

  memcached:
    image: "memcached:latest"
    restart: on-failure

  mailhog:
    image: mailhog/mailhog
    environment:
      MH_UI_WEB_PATH: mailhog
    restart: on-failure

  db:
    image: mysql:8
    ports: 
      - "3306:3306"
    hostname: host.docker.internal
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: local
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    tmpfs:
      - /var/lib/mysql
    restart: on-failure

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      ADMINER_DESIGN: lucas-sandery
      ADMINER_DEFAULT_SERVER: db
    restart: on-failure